name: "Dependaction - Rebase"
description: "Rebase PRs after push to main branch"
inputs:
  token:
    required: false
    default: ${{ github.token }}
  base-branch: # root directories to search for deps
    description: ""
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: peter-evans/rebase@v1
      with:
        token: ${{ inputs.token }}
        base: ${{ inputs.base-branch }}
        include-labels: dependaction
